# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('date_sent', models.DateField(auto_now_add=True)),
                ('important', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'System Messages',
                'ordering': ['-date_sent'],
            },
        ),
        migrations.CreateModel(
            name='UserPrefs',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prefs', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('birth_month', models.IntegerField(blank=True, null=True)),
                ('birth_day', models.IntegerField(blank=True, null=True)),
                ('ethnicity', models.CharField(choices=[('White', 'White'), ('European', 'European'), ('African American', 'African American'), ('Hispanic / Latino', 'Hispanic / Latino'), ('Asian', 'Asian'), ('Middle Eastern', 'Middle Eastern'), ('Pacific Islander', 'Pacific Islander'), ('Native American / Alaskan', 'Native American / Alaskan')], default='White', max_length=25)),
                ('height_feet', models.IntegerField(blank=True, null=True)),
                ('height_inches', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('determination', models.CharField(choices=[('Gain Weight', 'Gain Weight'), ('Maintain Weight', 'Maintain Weight'), ('Lose Weight', 'Lose Weight')], default='Gain Weight', max_length=15)),
                ('time_zone', timezone_field.fields.TimeZoneField(blank=True, null=True)),
                ('date_format', models.CharField(choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY')], default='MM/DD/YYYY', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'User Preferences',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sys_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='users_read',
            field=models.ManyToManyField(blank=True, related_name='read_sys_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
